version: "3"

services:
  api:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    container_name: tactech-back

  client:
    build: ./frontend
    ports:
      - "3000:80"
    container_name: tactech-front

  db:
    image: mongo
    ports:
      - "27018:27017"
    container_name: tactech-mongo
    command: --quiet